### ISSUE TITLE
为什么基于damo/mgeo_geographic_entity_alignment_chinese_base继续训练的模型精度会随着epoch的增加而降低？

### ISSUE THREAD

**Issue by maguoyu2023** [PhantomGrapes/MGeoExample#1]
这是训练日志的可视化
<img width="656" alt="loss" src="https://user-images.githubusercontent.com/123285041/217692126-ddc45f44-79af-494f-8898-420ee6a75404.png">
<img width="488" alt="macro_f1" src="https://user-images.githubusercontent.com/123285041/217692140-fe9e7a4c-52c8-4799-972b-7bfe9f44e695.png">
[train_log.csv](https://github.com/PhantomGrapes/MGeoExample/files/10691679/train_log.csv)
[eval_log.csv](https://github.com/PhantomGrapes/MGeoExample/files/10691682/eval_log.csv)

**Comment by bcol23** [comment]
因为训练数据比较少，训练epoch多了容易过拟合，基本上3个epochs左右差不多了，可以使用grid search搜索一下最优的参数，或者在dev集上early stop，用第三个epoch模型的ckeckpoint
