### ISSUE TITLE
请问是否有计划发布Query-POI match的recall任务的权重？

### ISSUE THREAD

**Issue by LightChaser666** [PhantomGrapes/MGeoExample#2]
你好，非常感谢你们的优秀工作，填补了此领域公开benchmark以及预训练权重的稀缺。

但我有一点疑惑：在尝试做POI retrieval的任务时，我没有在仓库中看到用于recall任务的MGeo预训练权重（注明年后发布的recall任务数据集似乎是已经发布了）。其他五个任务的模型都提供了下载。我想请问是否是我的疏漏？

如果你们的确没有提供recall任务相关，请问你们是否有计划发布这一预训练权重呢？如果不能，我怎样做才能复现论文中的对应结果？

再次感谢！

**Comment by PhantomGrapes** [comment]
预训练权重以及数据都在主repo中公开了https://github.com/PhantomGrapes/MGeo
