### ISSUE TITLE
关于Query-Poi任务数据量大的问题

### ISSUE THREAD

**Issue by seokjin954** [PhantomGrapes/MGeoExample#3]
您好，在给出的示例中是输入一条query然后返回3个待选地址的相似度，但是实际应用中待选地址是一个很大的地址库，比如有十几万待选地址，这样的话推理起来往往造成内存溢出，想问这种情况需要怎么做,期待您的回复，谢谢

**Comment by PhantomGrapes** [comment]
建议使用双塔结构，详情见论文以及对应的代码repo https://github.com/PhantomGrapes/MGeo
